exclude_paths:
  - 'public/index.php'
  - 'public/.htaccess'
  - 'public/js/*'
  - 'public/css/*'
  - 'src/Kernel.php'
  - 'config/**/*'
  - 'migrations/*'
  - 'bin/*'
  - 'tests'
  - 'translations'
  - 'UML/**/*'
  - 'LICENCE'
  - 'README.md'
  - '.htaccess'
  - '.env'
  - '.env.test'
  - '.gitignore'
  - '.php-version'
  - 'composer.json'
  - 'composer.lock'
  - 'composer.phar'
  - 'phpunit.xml.dist'
  - 'symfony.lock'