---
exclude_paths:
  - '_UML/**/*'
  - 'bin/*'
  - 'config/**/*'
  - 'migrations/*'
  - 'public/index.php'
  - 'public/.htaccess'
  - 'public/js/aos.js'
  - 'public/js/bootstrap.bundle.js'
  - 'public/js/bootstrap.bundle.min.js'
  - 'public/js/bootstrap.js'
  - 'public/js/bootstrap.min.js'
  - 'public/js/counterup.min.js'
  - 'public/js/isotope.pkgd.js'
  - 'public/js/isotope.pkgd.min.js'
  - 'public/js/jquery.easing.min.js'
  - 'public/js/jquery.min.js'
  - 'public/js/jquery.waypoints.min.js'
  - 'public/js/LICENSE'
  - 'public/js/main.js'
  - 'public/js/owl.carousel.js'
  - 'public/js/owl.carousel.min.js'
  - 'public/js/README.md'
  - 'public/js/venobox.js'
  - 'public/js/venobox.min.js'
  - 'public/img/**/*'
  - 'public/video/**/*'
  - 'public/css/ajax-loader.gif'
  - 'public/css/animations.css'
  - 'public/css/aos.css'
  - 'public/css/bootstrap.css'
  - 'public/css/bootstrap-grid.css'
  - 'public/css/bootstrap-grid.min.css'
  - 'public/css/boxicons.min.css'
  - 'public/css/bootstrap-reboot.css'
  - 'public/css/bootstrap-reboot.min.css'
  - 'public/css/boxicons.css'
  - 'public/css/icofont.min.css'
  - 'public/css/owl.carousel.css'
  - 'public/css/owl.carousel.min.css'
  - 'public/css/owl.theme.default.css'
  - 'public/css/owl.theme.green.css'
  - 'public/css/owl.video.play.png'
  - 'public/css/transformations.css'
  - 'public/css/venobox.css'
  - 'public/css/venobox.min.css'
  - 'public/fonts/*'
  - 'migrations/*'
  - 'bin/*'
  - 'tests'
  - 'translations'
  - 'UML/**/*'
  - 'var/**/*'
  - 'vendor/**/*'
  - 'LICENCE'
  - 'README.md'
  - '.htaccess'
  - '.env'
  - '.env.test'
  - '.gitignore'
  - '.php-version'
  - 'composer.json'
  - 'composer.lock'
  - 'composer.phar'
  - 'phpunit.xml.dist'
  - 'symfony.lock'
  - 'src/Kernel.php'
  - 'src/Form/*'
  - 'src/DataFixtures/AppFixtures.php'
  - 'src/Repository/*'